### ISSUE TITLE
Syntax error for generated imports

### ISSUE THREAD

**Issue by Nukiloco** [jycouet/kitql#173]
### Describe the bug

Having this ``.kitql.yaml``
```
generates:
  ./src/lib/server/gen/kitql:
    modules:
      - ./src/lib/server/modules/*
    actions:
      # createEnumsModule:
      #   prismaFile: ./prisma/schema.prisma
      mergeModuleTypedefs: true
      mergeModuleResolvers: true
      mergeContexts: true
      mergeModules: true

    moduleOutputFolder: gen/kitql
    importBaseTypesFrom: ./src/lib/server/server/gen/graphql-base-types.ts
```
with this file layout
- src
  - lib
    - server
      - modules
        - user
          - db
            - prisma files 
          - gen
            - generated files
          - resolvers
            - typescript files
          - schema
            - typedef gql files

is producing this file output
``_appModules.ts``
```
import { userModule } from '..\..\modules\user';

export const modules = [
  userModule,
];
```

which produces this error
```
C:/Users/user/Desktop/Nukiloco/Projects/Project/full/src/lib/server/gen/kitql/_appModules.ts:1:43: ERROR: Syntax error "s"


[33mSyntax error "s"[39m
1  |  import { userModule } from '..\..\modules\user';
   |                                             ^
2  |  
3  |  export const modules = [

```

### Your Example Website or App

local

### Steps to Reproduce the Bug or Issue

Described above

### Expected behavior

I expected it to not return the error above when going to http://localhost:8000/api/graphql

### Platform

- OS: Windows
- NodeJS: 16.14.1
- `@kitql/*` version: ^0.7.0

### Additional context

I will probably fill in the rest of the information of the bug report later. I'm very tired right now.

**Comment by Nukiloco** [comment]
https://github.com/Nukiloco/syntax_error_import_problem
Here is a repo that you can clone. Just run gen, then run dev.
After that then go to localhost:8000/api/graphql

**Comment by jycouet** [comment]
You should add in your user module: `index.ts`

That looks something like: 
```ts
import { createModule } from 'graphql-modules';
import { resolvers } from './$kitql/resolvers';
import { typeDefs } from './$kitql/typedefs';

export const __initModule = createModule({
	id: 'init-module',
	typeDefs,
	resolvers
});
```

I will have more time beginning of the week to have a look.

**Comment by Nukiloco** [comment]
https://github.com/jycouet/kitql/blob/main/packages/module-codegen/src/actionModules.ts#L12

this is where the issue is occurring and I think this is the fix for it

```
function toForwardSlash(path) {
    return path.replace(/\\/g, `/`)
}
```

and replacing line 206 in ``actionModules.ts`` with
```
	const moduleRelativePath = toForwardSlash(path.relative(outputFolder, module.directory));
```

**Comment by jycouet** [comment]
Good catch. 👍

_Hooo, I see. `OS: Windows`_
I'll have to check if it's working for WSL as well.

You wanna create the PR? Or I will do it later?

**Comment by Nukiloco** [comment]
> Good catch. 👍
> 
> _Hooo, I see. `OS: Windows`_ I'll have to check if it's working for WSL as well.
> 
> You wanna create the PR? Or I will do it later?

Yea when I saw the output get generated correctly on stackblitz and saw that the path was using backward slashes. I immediately knew this was probably a windows:tm: problem.

Where would a helper function like ``toForwardSlash`` be put at?

**Comment by Nukiloco** [comment]
When I ran yarn, everything seem to install just fine. But vscode git is listing every file as changed even though I have only changed two files?

warning: LF will be replaced by CRLF in packages/template/package.json.
The file will have its original line endings in your working directory

Just copied from the amount of spam that came from ``git diff``. Seems like windows changed all the line endings?

**Comment by jycouet** [comment]
Should be fixed next version

**Comment by Nukiloco** [comment]
This is still happening with the newest version as its still using backslashes

**Comment by Nukiloco** [comment]
```
dataResolvers.push(`import { resolvers as ${getFileWODots(resolver)} } from '${path.join(relativeResolversFolder, getFileWOTS(resolver))}';`);
```
path.join causes the path to use backslashes instead so it has to be converted back to posix

**Comment by jycouet** [comment]
I know it's posix now.
I did spin up a window for you, git, node, ... and tested with this syntax and was working on windows. 

I'll reopen the bug, could you paste the error you get here please?

**Comment by Nukiloco** [comment]
error message that appears
```
esolversmutationodule for ssr: ....
esolversmutation load module for ssr: ....
    at instantiateModule (C:\Users\user\Desktop\Nukiloco\Projects\Project\full\node_modules\.pnpm\vite@2.9.13\node_modules\vite\dist\node\chunks\dep-80fe9c6b.js:50206:15)
```

incorrect generated file
```
import { resolvers as mutation } from '..\..\resolvers\mutation';
import { resolvers as query } from '..\..\resolvers\query';
import { resolvers as scalar } from '..\..\resolvers\scalar';

export const resolvers = [
  mutation,
  query,
  scalar,
];
```

**Comment by jycouet** [comment]
Just to confirm, now
```ts
import { userModule } from '..\..\modules\user';

export const modules = [
  userModule,
];
```

is:
```ts
import { userModule } from '../.../modules/user';

export const modules = [
  userModule,
];
```

And the `posix` import is working well, right?

I forgot to put `posix` also at the `join` of resolvers. But I want to confirm with you that it's solving the issue in the module before proceeding for resolvers.

**Comment by Nukiloco** [comment]
When I changed ``path.join ``to ``path.posix.join ``yes its working now.

**Comment by jycouet** [comment]
Should be fixed.
Can you check please?
